os: linux
language: python
python: "3.7"
dist: bionic
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libgtk2.0-dev libva-dev libvdpau-dev
install:
  - pip install conan
  - conan user
script:
  - mkdir build
  - cd build  
  - conan install .. -o opencv:shared=True  -s compiler.libcxx=libstdc++11
  - cmake .. -G "Unix Makefiles"
  - cmake --build .
  - cd ./bin
  - ./CvPlotTests
