version: 1.0.{build}
image: Visual Studio 2017
environment:
  PYTHON: "C:\\Python38"
platform:
  - x64

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - cmd: path
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan install ..
  - cmd: cmake .. -G "Visual Studio 15 2017 Win64"
  - cmd: cmake --build . --config Release

test_script:
  - cmd: cd bin
  - cmd: CvPlotTests.exe